-- SMPP 通道配置扩展：增加绑定类型、目标 TON/NPI 字段
USE sms_platform;

ALTER TABLE channel
    ADD COLUMN smpp_bind_type VARCHAR(20) DEFAULT 'BIND_TRX' COMMENT 'SMPP绑定类型: BIND_TRX/BIND_TX/BIND_RX',
    ADD COLUMN smpp_dest_ton  VARCHAR(20) DEFAULT 'INTERNATIONAL' COMMENT '目标地址 TypeOfNumber: INTERNATIONAL/NATIONAL/UNKNOWN/ALPHANUMERIC',
    ADD COLUMN smpp_dest_npi  VARCHAR(20) DEFAULT 'ISDN' COMMENT '目标地址 NPI: ISDN/UNKNOWN/NATIONAL/PRIVATE';
